[Match]
Architecture=x86-64

[Content]
# List taken from https://gitlab.com/fedora/ostree/ci-test/-/blob/main/packages/common.yaml
Packages=
    alsa-sof-firmware
    amd-ucode-firmware
    cirrus-audio-firmware
    intel-audio-firmware
    intel-lpmd
    intel-vsc-firmware
    libva-intel-media-driver
    mcelog
    microcode_ctl
    thermald
    virtualbox-guest-additions