VolatilePackages=
    systemd-container

Packages=
    bolt
    brightnessctl
    ddcutil
    default-fonts
    default-fonts-core-emoji
    distribution-gpg-keys
    distrobox
    fastfetch
    fcitx5-chinese-addons
    fcitx5-mozc
    fcitx5-rime
    flatpak
    git-core
    glibc-all-langpacks
    glycin-thumbnailer
    gnome-keyring
    gnome-keyring-pam
    gnupg2-scdaemon
    google-noto-color-emoji-fonts
    google-noto-emoji-fonts
    gst-thumbnailers
    just
    lshw
    nano-default-editor
    ncurses
    nm-connection-editor
    nmtui
    openrgb-udev-rules
    orca
    steam-devices
    tailscale
    tesseract
    xdg-desktop-portal-gnome
    xdg-desktop-portal-gtk
    xdg-terminal-exec
    xdg-user-dirs

# FIXME: Remove once https://github.com/systemd/mkosi/pull/4390 is merged
[Build]
ToolsTreePackages=
    passwd