---
name: Build disk image
on:
  workflow_dispatch:

env:
  IMAGE_DESC: "Larimar Next"
  IMAGE_KEYWORDS: "bootc,fedora,arm64,x86_64,gnome"
  IMAGE_LOGO_URL: "https://avatars.githubusercontent.com/u/121560464?s=400&v=4"
  IMAGE_NAME: "${{ github.event.repository.name }}"
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"
  DEFAULT_TAG: "latest"
jobs:
  build_release:
    name: Build and release disk image
    permissions:
      contents: read
      packages: read
      id-token: write
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        platform: ["amd64", "arm64"]
    runs-on: ${{ matrix.platform == 'amd64' && 'ubuntu-26.04' || 'ubuntu-26.04-arm' }}

    steps:
      - name: Prepare environment
        run: |
          # Lowercase the image uri
          echo "IMAGE_REGISTRY=${IMAGE_REGISTRY,,}" >> ${GITHUB_ENV}
          echo "IMAGE_NAME=${IMAGE_NAME,,}" >> ${GITHUB_ENV}
    
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: true

      - name: Maximize build space
        if: inputs.platform != 'arm64'
        uses: ublue-os/remove-unwanted-software@cc0becac701cf642c8f0a6613bbdaf5dc36b259e # v9
        with:
          remove-codeql: true

      - name: Pull the image
        env:
          IMAGE_REGISTRY: ${{ env.IMAGE_REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          DEFAULT_TAG: ${{ env.DEFAULT_TAG }}
        run: sudo podman pull ${IMAGE_REGISTRY}/${IMAGE_NAME}:${DEFAULT_TAG}

      - name: Build ISO
        id: build-iso
        uses: osbuild/bootc-image-builder-action@main
        with:
          config-file: './iso.toml'
          image: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DEFAULT_TAG }}
          types: anaconda-iso
          rootfs: btrfs
          additional-args: --use-librepo=True

      - name: Upload Artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v5
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.platform }}
          path: ${{ steps.build-iso.outputs.output-directory }}
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
          overwrite: true